// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSingleAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddSingleAccount'](arg1, arg2, arg3);
}

export function ApplySeamlessPatch(arg1) {
  return window['go']['main']['App']['ApplySeamlessPatch'](arg1);
}

export function AutoSwitchToNext(arg1, arg2) {
  return window['go']['main']['App']['AutoSwitchToNext'](arg1, arg2);
}

export function CheckPatchStatus(arg1) {
  return window['go']['main']['App']['CheckPatchStatus'](arg1);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function DeleteExpiredAccounts() {
  return window['go']['main']['App']['DeleteExpiredAccounts']();
}

export function DeleteFreePlanAccounts() {
  return window['go']['main']['App']['DeleteFreePlanAccounts']();
}

export function FindWindsurfPath() {
  return window['go']['main']['App']['FindWindsurfPath']();
}

export function GetAllAccounts() {
  return window['go']['main']['App']['GetAllAccounts']();
}

export function GetCurrentWindsurfAuth() {
  return window['go']['main']['App']['GetCurrentWindsurfAuth']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetWindsurfAuthPath() {
  return window['go']['main']['App']['GetWindsurfAuthPath']();
}

export function ImportByAPIKey(arg1) {
  return window['go']['main']['App']['ImportByAPIKey'](arg1);
}

export function ImportByEmailPassword(arg1) {
  return window['go']['main']['App']['ImportByEmailPassword'](arg1);
}

export function ImportByJWT(arg1) {
  return window['go']['main']['App']['ImportByJWT'](arg1);
}

export function ImportByRefreshToken(arg1) {
  return window['go']['main']['App']['ImportByRefreshToken'](arg1);
}

export function RefreshAccountQuota(arg1) {
  return window['go']['main']['App']['RefreshAccountQuota'](arg1);
}

export function RefreshAllQuotas() {
  return window['go']['main']['App']['RefreshAllQuotas']();
}

export function RefreshAllTokens() {
  return window['go']['main']['App']['RefreshAllTokens']();
}

export function RestoreSeamlessPatch(arg1) {
  return window['go']['main']['App']['RestoreSeamlessPatch'](arg1);
}

export function SwitchAccount(arg1) {
  return window['go']['main']['App']['SwitchAccount'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
